import type { RandomEventConfig } from '../types/game';

export const RANDOM_EVENTS: RandomEventConfig[] = [
  {
    id: 'publicShowReview',
    title: '公演小复盘',
    description: '公演结束后，小獭和大家一起复盘了几个细节。',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['练习', '舞台', '日常'],
    baseWeight: 10,
    choices: [
      {
        id: 'markDetails',
        label: '记下细节',
        resultText: '她把需要注意的地方认真写下，下一次舞台会更稳。',
        effects: {
          performance: 2,
          dance: 1,
          stress: 1,
        },
        b50Bonus: 1,
      },
      {
        id: 'thankTeam',
        label: '感谢队友',
        resultText: '小獭认真向队友道谢，舞台上的默契多了一点。',
        effects: {
          mood: 3,
          fanLoyalty: 1,
        },
      },
    ],
  },
  {
    id: 'trainingFatigue',
    title: '训练疲劳',
    description: '连续练习后，小獭的肩膀有点发紧。',
    rarity: 'common',
    tone: 'negative',
    triggerTags: ['练习', '透支', '压力'],
    baseWeight: 9,
    choices: [
      {
        id: 'stretch',
        label: '拉伸放松',
        resultText: '小獭放慢节奏做了拉伸，疲劳没有继续堆起来。',
        effects: {
          energy: 4,
          stress: -2,
        },
      },
      {
        id: 'finishSet',
        label: '完成这组',
        resultText: '她还是把最后一组练完了，成长有一点，但状态更吃紧。',
        effects: {
          vocal: 1,
          dance: 1,
          energy: -5,
          stress: 4,
        },
      },
    ],
  },
  {
    id: 'fanSmallInteraction',
    title: '粉丝小互动',
    description: '营业间隙，有粉丝认真说起最近被小獭鼓励到了。',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['粉丝', '营业', '应援'],
    baseWeight: 10,
    choices: [
      {
        id: 'respondWarmly',
        label: '温柔回应',
        resultText: '小獭把这份喜欢好好接住，粉丝之间的陪伴感更强了。',
        effects: {
          fanLoyalty: 2,
          mood: 2,
        },
        electionBonus: 1,
      },
      {
        id: 'rememberName',
        label: '记住名字',
        resultText: '她悄悄记住了对方的名字，下一次见面会更亲近。',
        effects: {
          fanLoyalty: 3,
          charm: 1,
        },
      },
    ],
  },
  {
    id: 'scheduleInterlude',
    title: '行程小插曲',
    description: '今天的行程中间出现了一点小变化。',
    rarity: 'common',
    tone: 'mixed',
    triggerTags: ['日常', '外务', '恢复'],
    baseWeight: 8,
    choices: [
      {
        id: 'adjustPace',
        label: '调整节奏',
        resultText: '小獭顺着变化重新安排节奏，状态没有被打乱。',
        effects: {
          mood: 2,
          stress: -1,
        },
      },
      {
        id: 'keepSchedule',
        label: '按计划推进',
        resultText: '她稳稳完成了原计划，只是体力消耗比预想多一点。',
        effects: {
          popularity: 1,
          energy: -3,
        },
      },
    ],
  },
  {
    id: 'stageRhythmSlip',
    title: '舞台节奏失衡',
    description: '排练时节奏一度乱掉，小獭有些着急。',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['舞台', 'B50', '透支'],
    baseWeight: 7,
    choices: [
      {
        id: 'slowReview',
        label: '慢速复盘',
        resultText: '她把节奏拆开重来，虽然累，但舞台理解更清楚了。',
        effects: {
          performance: 3,
          energy: -4,
          stress: 3,
        },
        b50Bonus: 2,
      },
      {
        id: 'pausePractice',
        label: '暂停一下',
        resultText: '小獭先把呼吸稳住，压力慢慢降了下来。',
        effects: {
          mood: 3,
          stress: -5,
        },
      },
    ],
  },
  {
    id: 'supportFatigue',
    title: '应援疲劳',
    description: '粉丝群里最近有点疲惫，小獭也感受到了这份压力。',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['粉丝', '应援', '压力'],
    baseWeight: 6,
    choices: [
      {
        id: 'slowCompanion',
        label: '慢慢陪伴',
        resultText: '小獭没有催促大家，只是稳稳把陪伴传递回去。',
        effects: {
          fanLoyalty: 3,
          mood: 2,
        },
      },
      {
        id: 'pushSupport',
        label: '努力动员',
        resultText: '动员带来了一点热度，但压力也更明显。',
        effects: {
          popularity: 2,
          fans: 20,
          stress: 5,
        },
        electionBonus: 2,
      },
    ],
  },
  {
    id: 'outsideBuzz',
    title: '外务小出圈',
    description: '一段外务片段被路人转发，小獭被更多人看见了。',
    rarity: 'rare',
    tone: 'positive',
    triggerTags: ['外务', '曝光', '舆论'],
    baseWeight: 7,
    choices: [
      {
        id: 'followTopic',
        label: '顺势营业',
        resultText: '小獭顺着话题认真营业，新的关注变成了真实好感。',
        effects: {
          popularity: 4,
          charm: 2,
          fans: 35,
          stress: 2,
        },
        electionBonus: 2,
      },
      {
        id: 'stayNatural',
        label: '自然一点',
        resultText: '她保持自然表达，路人对这份松弛感印象不错。',
        effects: {
          popularity: 3,
          mood: 2,
        },
      },
    ],
  },
  {
    id: 'styleDiscussion',
    title: '风格讨论',
    description: '新的物料让粉丝开始讨论小獭更适合哪种风格。',
    rarity: 'rare',
    tone: 'mixed',
    triggerTags: ['风格', '形象', '舆论'],
    baseWeight: 7,
    choices: [
      {
        id: 'clarifyStyle',
        label: '明确风格',
        resultText: '小獭更清楚自己想呈现的样子，辨识度提升了。',
        effects: {
          style: 4,
          charm: 2,
          stress: 2,
        },
      },
      {
        id: 'listenMore',
        label: '多听意见',
        resultText: '她认真听取不同反馈，粉丝也感到自己被看见。',
        effects: {
          fanLoyalty: 2,
          mood: 2,
        },
      },
    ],
  },
  {
    id: 'fanLetter',
    title: '粉丝来信',
    description: '收到了一封粉丝来信，小獭看完后眼睛亮亮的。',
    eventCgKey: 'fanLetterCg',
    galleryId: 'fanLetterCg',
    rarity: 'rare',
    tone: 'positive',
    triggerTags: ['粉丝', '应援', '营业'],
    baseWeight: 8,
    choices: [
      {
        id: 'reply',
        label: '认真回复',
        resultText: '小獭认真写下回复，心里被温柔填满了。',
        effects: {
          mood: 8,
          fans: 20,
          fanLoyalty: 3,
        },
        electionBonus: 2,
      },
      {
        id: 'keep',
        label: '收藏起来',
        resultText: '小獭把来信收进小盒子，偷偷开心了一整天。',
        effects: {
          mood: 5,
          fanLoyalty: 1,
        },
      },
    ],
  },
  {
    id: 'fanCreation',
    title: '粉丝二创出圈',
    description: '有粉丝剪的小獭舞台片段突然被更多人看见了。',
    eventCgKey: 'fanCreationCg',
    galleryId: 'fanCreationCg',
    rarity: 'superRare',
    tone: 'positive',
    triggerTags: ['粉丝', '创作', '应援'],
    baseWeight: 8,
    choices: [
      {
        id: 'interact',
        label: '温柔互动',
        resultText: '小獭认真感谢粉丝，新的路人也被这份可爱吸引了。',
        effects: {
          popularity: 4,
          fans: 80,
          fanLoyalty: 3,
          stress: 4,
        },
        electionBonus: 4,
      },
      {
        id: 'quietLike',
        label: '悄悄点赞',
        resultText: '小獭悄悄点了赞，粉丝之间的陪伴感更强了。',
        effects: {
          mood: 4,
          fanLoyalty: 4,
        },
      },
    ],
  },
  {
    id: 'stageMistake',
    title: '舞台小失误',
    description: '彩排时出现了一个小失误，小獭有点在意。',
    eventCgKey: 'stageMistakeCg',
    galleryId: 'stageMistakeCg',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['舞台', '练习', '透支'],
    baseWeight: 7,
    choices: [
      {
        id: 'review',
        label: '复盘问题',
        resultText: '小獭把动作重新拆开练习，舞台稳定度提升了。',
        effects: {
          performance: 4,
          dance: 2,
          energy: -5,
          stress: 3,
        },
        b50Bonus: 3,
      },
      {
        id: 'comfort',
        label: '安慰小獭',
        resultText: '被好好安慰后，小獭又找回了笑容。',
        effects: {
          mood: 8,
          stress: -4,
        },
      },
    ],
  },
  {
    id: 'extraPractice',
    title: '练习室加练',
    description: '小獭觉得今天还能再努力一点。',
    eventCgKey: 'extraPracticeCg',
    galleryId: 'extraPracticeCg',
    rarity: 'rare',
    tone: 'mixed',
    triggerTags: ['练习', '舞台'],
    baseWeight: 8,
    choices: [
      {
        id: 'continue',
        label: '继续加练',
        resultText: '加练很辛苦，但小獭的舞台基础更扎实了。',
        effects: {
          vocal: 3,
          dance: 3,
          performance: 2,
          energy: -8,
          stress: 5,
        },
        b50Bonus: 2,
      },
      {
        id: 'restNow',
        label: '及时休息',
        resultText: '小獭乖乖补充体力，状态轻轻回升。',
        effects: {
          energy: 8,
          mood: 3,
          stress: -5,
        },
      },
    ],
  },
  {
    id: 'styleChallenge',
    title: '想挑战不同风格',
    description: '小獭看着新的造型提案，眼睛里闪过一点期待。',
    eventCgKey: 'styleChallengeCg',
    galleryId: 'styleChallengeCg',
    rarity: 'superRare',
    tone: 'positive',
    triggerTags: ['风格', '形象', '舆论'],
    baseWeight: 7,
    choices: [
      {
        id: 'tryNew',
        label: '大胆尝试',
        resultText: '新的风格让小獭多了一种可瓜可花的可能性。',
        effects: {
          style: 6,
          charm: 2,
          stress: 4,
        },
      },
      {
        id: 'staySteady',
        label: '稳一点来',
        resultText: '小獭先把熟悉的表达做得更细，舞台感也更自然了。',
        effects: {
          performance: 3,
          fanLoyalty: 2,
        },
      },
    ],
  },
  {
    id: 'summerInvite',
    title: '夏日邀约',
    description: '收到了一份夏日活动邀约。',
    eventCgKey: 'summerInviteCg',
    galleryId: 'summerInviteCg',
    rarity: 'superRare',
    tone: 'positive',
    triggerTags: ['外务', '曝光', '粉丝'],
    baseWeight: 6,
    choices: [
      {
        id: 'join',
        label: '参加活动',
        resultText: '夏日活动顺利完成，小獭收获了新的关注。',
        effects: {
          popularity: 6,
          fans: 70,
          energy: -10,
          style: 3,
        },
        flags: {
          summerJoined: true,
          summerActive: true,
        },
        electionBonus: 3,
      },
      {
        id: 'decline',
        label: '暂时婉拒',
        resultText: '小獭把节奏放慢了一点，安心调整状态。',
        effects: {
          energy: 5,
          mood: 2,
          stress: -3,
        },
      },
    ],
  },
  {
    id: 'lowMood',
    title: '心情低落',
    description: '连续忙碌之后，小獭今天有点提不起精神。',
    eventCgKey: 'lowMoodCg',
    galleryId: 'lowMoodCg',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['透支', '压力', '恢复'],
    baseWeight: 10,
    triggerCondition: (state) => state.mood < 55 || state.stress >= 65,
    choices: [
      {
        id: 'talk',
        label: '陪她聊聊',
        resultText: '被认真听见之后，小獭的心情慢慢软了下来。',
        effects: {
          mood: 10,
          stress: -8,
        },
      },
      {
        id: 'pushThrough',
        label: '完成排练',
        resultText: '小獭撑着完成排练，舞台经验增加了，但压力也更明显。',
        effects: {
          performance: 3,
          energy: -5,
          stress: 5,
        },
        b50Bonus: 1,
      },
    ],
  },
  {
    id: 'secretHappy',
    title: '被夸奖后偷偷开心',
    description: 'Staff 夸小獭今天进步很明显，她表面镇定，耳朵却红红的。',
    eventCgKey: 'secretHappyCg',
    galleryId: 'secretHappyCg',
    rarity: 'superRare',
    tone: 'positive',
    triggerTags: ['日常', '粉丝', '恢复'],
    baseWeight: 7,
    choices: [
      {
        id: 'acceptPraise',
        label: '大方接受',
        resultText: '小獭把夸奖好好收下，笑容也更有自信了。',
        effects: {
          mood: 6,
          charm: 2,
        },
      },
      {
        id: 'writeNotebook',
        label: '记进本子',
        resultText: '她把这句话写进练习本，像给未来的自己留下一颗星。',
        effects: {
          performance: 2,
          fanLoyalty: 2,
        },
      },
    ],
  },
];

export const FALLBACK_EVENT: RandomEventConfig = {
  id: 'dailyMoment',
  title: '普通但重要的一天',
  description: '没有特别大的事件，但小獭还是认真完成了今天的安排。',
  rarity: 'common',
  tone: 'mixed',
  triggerTags: ['日常', '恢复'],
  baseWeight: 1,
  choices: [
    {
      id: 'steady',
      label: '稳稳收尾',
      resultText: '平凡的一天也有小小积累，小獭把状态保持住了。',
      effects: {
        mood: 2,
        fanLoyalty: 1,
      },
    },
    {
      id: 'earlySleep',
      label: '早点休息',
      resultText: '小獭早早睡下，第二天醒来时眼睛又亮了起来。',
      effects: {
        energy: 6,
        stress: -3,
      },
    },
  ],
};
