import type { RandomEventConfig } from '../types/game';

export const RANDOM_EVENTS: RandomEventConfig[] = [
  {
    id: 'theaterSpotlight',
    type: 'positive',
    title: '剧场小高光',
    description: '这场表演里，她有一个瞬间被观众记住了。也许不是最中心的位置，但那一秒足够闪亮。',
    visualKey: 'extraPracticeCg',
    eventCgKey: 'extraPracticeCg',
    galleryId: 'extraPracticeCg',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['练习', '舞台', 'B50'],
    actionTypes: ['theaterTraining', 'stageFocus'],
    baseWeight: 12,
    cooldownMonths: 3,
    choices: [
      {
        id: 'polishMoment',
        label: '记住这个瞬间',
        description: '把有效的表现方式继续打磨。',
        resultText: '小獭把被记住的那个动作反复拆开，舞台上的确定感更强了。',
        effects: { stagePower: 4, supportPower: 1, fanCount: 30 },
        b50Bonus: 2,
      },
      {
        id: 'shareFeeling',
        label: '分享舞台感受',
        description: '把这份开心传递给粉丝。',
        resultText: '她认真说起舞台上的心情，粉丝也更愿意为下一次应援。',
        effects: { mood: 3, supportPower: 2, fanCount: 18 },
      },
    ],
  },
  {
    id: 'warmFanFeedback',
    type: 'positive',
    title: '粉丝反馈热烈',
    description: '一次普通的回应被粉丝反复提起。那些细小的真诚，慢慢变成了继续支持她的理由。',
    visualKey: 'fanLetterCg',
    eventCgKey: 'fanLetterCg',
    galleryId: 'fanLetterCg',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['粉丝', '营业', '应援'],
    actionTypes: ['fanService', 'stableOperation'],
    baseWeight: 13,
    cooldownMonths: 2,
    choices: [
      {
        id: 'respondCarefully',
        label: '认真回应',
        description: '把陪伴感继续接住。',
        resultText: '小獭把粉丝的喜欢稳稳接住，核心应援力也更踏实了。',
        effects: { supportPower: 3, fanCount: 45, mood: 2, fanFatigue: -2 },
        electionBonus: 2,
      },
      {
        id: 'keepSteady',
        label: '稳稳陪伴',
        description: '不催促，慢慢经营。',
        resultText: '没有突然的爆发，但留下来的人更愿意继续陪她走下去。',
        effects: { supportPower: 4, fanFatigue: -3, pressure: -1 },
      },
    ],
  },
  {
    id: 'outsideAttention',
    type: 'positive',
    title: '外部关注',
    description: '一次外部露出让更多人开始搜索她的名字。陌生的目光正在变成新的入口。',
    visualKey: 'fanCreationCg',
    eventCgKey: 'fanCreationCg',
    galleryId: 'fanCreationCg',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['外务', '曝光', '路人盘'],
    actionTypes: ['outsideExposure', 'imageBuilding', 'specialSoloWork'],
    baseWeight: 11,
    cooldownMonths: 3,
    choices: [
      {
        id: 'followExposure',
        label: '顺势接住',
        description: '把路人关注转成真实入口。',
        resultText: '小獭没有被突然的目光吓住，反而让更多人看见了她的可爱。',
        effects: { influence: 5, resource: 2, fanCount: 55, pressure: 2 },
        electionBonus: 2,
      },
      {
        id: 'stayNatural',
        label: '自然表达',
        description: '保持自己的节奏。',
        resultText: '她没有刻意迎合，松弛的表达反而留下了更好的印象。',
        effects: { influence: 3, charm: 2, mood: 2 },
      },
    ],
  },
  {
    id: 'styleRemembered',
    type: 'positive',
    title: '风格被记住',
    description: '她的风格开始变得清晰。不是复制别人，而是让人一眼能想起她。',
    visualKey: 'styleChallengeCg',
    eventCgKey: 'styleChallengeCg',
    galleryId: 'styleChallengeCg',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['风格', '形象', '物料'],
    actionTypes: ['imageBuilding', 'specialStyleShift'],
    baseWeight: 10,
    cooldownMonths: 3,
    choices: [
      {
        id: 'strengthenStyle',
        label: '强化记忆点',
        description: '把辨识度做得更清楚。',
        resultText: '小獭找到了一种更像自己的表达，可爱和锋芒都更清晰了。',
        effects: { charm: 5, influence: 2, supportPower: 1 },
      },
      {
        id: 'listenFans',
        label: '听取反馈',
        description: '让风格变化更稳。',
        resultText: '她认真听完不同意见，新的尝试没有变成距离感。',
        effects: { charm: 2, supportPower: 2, pressure: -1 },
      },
    ],
  },
  {
    id: 'fanBaseStabilized',
    type: 'positive',
    title: '军心稳定',
    description: '没有突然爆发的声量，但粉丝盘变得更稳了。有人留下来，也有人重新找回继续陪伴的理由。',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['运营', '恢复', '粉丝'],
    actionTypes: ['stableOperation', 'restAndReflect'],
    baseWeight: 11,
    cooldownMonths: 2,
    choices: [
      {
        id: 'steadyRhythm',
        label: '稳定节奏',
        description: '让粉丝盘慢慢恢复。',
        resultText: '小獭没有急着追声量，而是把陪伴变成更稳定的日常。',
        effects: { supportPower: 3, fanFatigue: -4, pressure: -2 },
      },
      {
        id: 'smallPromise',
        label: '给一个小约定',
        description: '用温柔的话稳住期待。',
        resultText: '一个小小的约定让大家安心了很多，继续陪伴也变得更有方向。',
        effects: { supportPower: 2, mood: 3, fanCount: 18 },
      },
    ],
  },
  {
    id: 'trainingOverload',
    type: 'negative',
    title: '训练消耗过度',
    description: '加练的效果确实出现了，但身体也开始提醒她，不能一直硬撑。',
    visualKey: 'stageMistakeCg',
    eventCgKey: 'stageMistakeCg',
    galleryId: 'stageMistakeCg',
    rarity: 'common',
    tone: 'negative',
    triggerTags: ['练习', '舞台', '透支'],
    actionTypes: ['theaterTraining', 'stageFocus', 'specialIntensiveTraining'],
    baseWeight: 9,
    cooldownMonths: 2,
    choices: [
      {
        id: 'finishPractice',
        label: '把这组练完',
        description: '继续换一点成长。',
        resultText: '她还是咬牙练完了这一组，舞台理解更深，但状态更吃紧。',
        effects: { stagePower: 2, stamina: -7, pressure: 4 },
        b50Bonus: 1,
      },
      {
        id: 'stopBeforeWorse',
        label: '及时停下',
        description: '先避免疲劳扩大。',
        resultText: '小獭把训练记录好，先让身体缓下来。',
        effects: { stamina: 5, pressure: -3, mood: 1 },
      },
    ],
  },
  {
    id: 'fanServiceFatigue',
    type: 'negative',
    title: '营业疲劳',
    description: '营业频率变高之后，一部分粉丝开始担心这份热闹会不会太消耗她。',
    rarity: 'common',
    tone: 'negative',
    triggerTags: ['粉丝', '营业', '应援'],
    actionTypes: ['fanService', 'specialBirthdaySupport'],
    baseWeight: 9,
    cooldownMonths: 2,
    choices: [
      {
        id: 'keepMomentum',
        label: '维持热度',
        description: '短期继续冲一把。',
        resultText: '热度确实继续上去了，但疲惫感也一起被推高。',
        effects: { fanCount: 45, fanFatigue: 6, mood: -3, pressure: 2 },
        electionBonus: 1,
      },
      {
        id: 'softenPace',
        label: '放软节奏',
        description: '让喜欢变得不那么紧绷。',
        resultText: '小獭把节奏放轻，粉丝也更愿意用舒服的方式陪着她。',
        effects: { supportPower: 2, fanFatigue: -4, mood: 2 },
      },
    ],
  },
  {
    id: 'exposurePressure',
    type: 'negative',
    title: '曝光压力',
    description: '新的关注带来了机会，也带来了更多评价。小獭开始有点在意自己是不是表现得足够好。',
    rarity: 'common',
    tone: 'negative',
    triggerTags: ['外务', '曝光', '压力'],
    actionTypes: ['outsideExposure', 'specialSoloWork'],
    baseWeight: 8,
    cooldownMonths: 3,
    choices: [
      {
        id: 'faceComments',
        label: '正面接住',
        description: '把压力转成可见度。',
        resultText: '她认真接住外界的评价，影响力上去了，压力也更明显。',
        effects: { influence: 3, pressure: 5, supportPower: -1 },
      },
      {
        id: 'filterNoise',
        label: '过滤噪音',
        description: '让团队帮她挡掉一部分消耗。',
        resultText: '团队帮她整理反馈，小獭不用把每一句话都背在身上。',
        effects: { operation: 2, pressure: -4, resource: -1 },
      },
    ],
  },
  {
    id: 'styleDebate',
    type: 'negative',
    title: '路线争议',
    description: '新的形象方向让讨论变多了，有人喜欢，也有人一时不适应。',
    rarity: 'common',
    tone: 'negative',
    triggerTags: ['风格', '形象', '舆论'],
    actionTypes: ['imageBuilding', 'specialStyleShift'],
    baseWeight: 8,
    cooldownMonths: 3,
    choices: [
      {
        id: 'holdDirection',
        label: '坚持方向',
        description: '把风格做得更明确。',
        resultText: '小獭没有马上退回去，辨识度更强了，但争议也带来压力。',
        effects: { charm: 3, pressure: 4, supportPower: -1 },
      },
      {
        id: 'adjustExpression',
        label: '微调表达',
        description: '保留新鲜感，也照顾粉丝接受度。',
        resultText: '她把新风格调得更贴近自己，讨论慢慢变得温和。',
        effects: { charm: 2, supportPower: 1, pressure: -2 },
      },
    ],
  },
  {
    id: 'staminaOverdraft',
    type: 'risk',
    title: '体力透支',
    description: '连月的训练和外务让身体开始发出警讯。她还是想撑住，但状态已经不再像之前那样稳定。',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['透支', '恢复', '舞台'],
    baseWeight: 18,
    cooldownMonths: 2,
    riskKey: 'stamina',
    priority: 90,
    requiresAttention: true,
    triggerCondition: (state) => state.stamina <= 20,
    choices: [
      {
        id: 'pushThrough',
        label: '咬牙坚持',
        description: '继续换舞台和声量。',
        resultText: '小獭撑住了这次安排，但身体发出的警讯更明显了。',
        effects: { stagePower: 2, influence: 1, stamina: -8, pressure: 6 },
        riskLevel: 'major',
      },
      {
        id: 'adjustPace',
        label: '调整节奏',
        description: '先把身体稳回来。',
        resultText: '她暂时放慢安排，身体终于得到一点喘息。',
        effects: { stamina: 14, pressure: -6, fanCount: -10 },
      },
      {
        id: 'talkFans',
        label: '稳定沟通',
        description: '让粉丝理解节奏调整。',
        resultText: '小獭认真说明自己的状态，核心粉反而更愿意保护她。',
        effects: { supportPower: 2, fanFatigue: -6, resource: -1 },
      },
    ],
  },
  {
    id: 'pressureImbalance',
    type: 'risk',
    title: '高压失衡',
    description: '高位期待让每一次失误都被放大。她开始变得更在意评价，也更难放松下来。',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['压力', '舆论', '高位'],
    baseWeight: 18,
    cooldownMonths: 2,
    riskKey: 'pressure',
    priority: 92,
    requiresAttention: true,
    triggerCondition: (state) => state.pressure >= 80,
    choices: [
      {
        id: 'faceExpectation',
        label: '正面回应期待',
        description: '用更高声量接住压力。',
        resultText: '她努力把期待转化成表达，影响力上升，但压力没有真正消失。',
        effects: { influence: 2, pressure: 7, mood: -3 },
        riskLevel: 'major',
      },
      {
        id: 'restAndReflect',
        label: '休整沉淀',
        description: '先让心情和压力回落。',
        resultText: '她把脚步放慢一点，终于重新听见自己的呼吸。',
        effects: { pressure: -14, mood: 8, influence: -1 },
      },
      {
        id: 'teamShare',
        label: '团队分担',
        description: '用运营力分摊压力。',
        resultText: '团队帮她拆解评价和安排，小獭不再一个人硬扛。',
        effects: { operation: 3, resource: -2, pressure: -10 },
      },
    ],
  },
  {
    id: 'supportOverdraft',
    type: 'risk',
    title: '应援盘透支',
    description: '粉丝仍然愿意支持她，但长期高强度应援已经让一部分人感到疲惫。',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['粉丝', '应援', '疲劳'],
    baseWeight: 18,
    cooldownMonths: 2,
    riskKey: 'support',
    priority: 91,
    requiresAttention: true,
    triggerCondition: (state) => state.fanFatigue >= 70,
    choices: [
      {
        id: 'keepRanking',
        label: '继续冲榜',
        description: '短期把数字再推上去。',
        resultText: '粉丝数短期又涨了一点，但疲劳也被继续推高。',
        effects: { fanCount: 90, fanFatigue: 9, pressure: 3 },
        riskLevel: 'major',
      },
      {
        id: 'comfortCoreFans',
        label: '安抚核心粉',
        description: '先修复应援盘。',
        resultText: '小獭没有催促大家，只是认真把感谢说清楚。',
        effects: { supportPower: 3, fanFatigue: -12, mood: 2 },
      },
      {
        id: 'steadyOperation',
        label: '稳定运营',
        description: '降低消耗，慢慢恢复。',
        resultText: '节奏慢下来以后，粉丝盘终于不再那么紧绷。',
        effects: { fanFatigue: -18, influence: -2, operation: 2 },
      },
    ],
  },
  {
    id: 'lowMoodSwing',
    type: 'risk',
    title: '状态低落',
    description: '她没有停下脚步，只是偶尔会在练习室的镜子前沉默很久。',
    visualKey: 'lowMoodCg',
    eventCgKey: 'lowMoodCg',
    galleryId: 'lowMoodCg',
    rarity: 'rare',
    tone: 'negative',
    triggerTags: ['压力', '恢复', '低落'],
    baseWeight: 18,
    cooldownMonths: 2,
    riskKey: 'mood',
    priority: 89,
    requiresAttention: true,
    triggerCondition: (state) => state.mood <= 25,
    choices: [
      {
        id: 'keepTraining',
        label: '继续训练',
        description: '用训练找回确定感。',
        resultText: '练习让她暂时找到了方向，但低落并没有完全散开。',
        effects: { stagePower: 2, mood: -6, pressure: 3 },
        riskLevel: 'warning',
      },
      {
        id: 'slowDown',
        label: '放慢节奏',
        description: '先把心情照顾好。',
        resultText: '小獭给自己留出一点空白，心情慢慢回到了可承受的位置。',
        effects: { mood: 14, pressure: -7, stamina: 3 },
      },
      {
        id: 'connectFans',
        label: '和粉丝连接',
        description: '用陪伴感重新获得力量。',
        resultText: '她从粉丝那里重新感受到被需要，眼睛又亮了一点。',
        effects: { supportPower: 3, mood: 6, stamina: -3 },
      },
    ],
  },
  {
    id: 'quietRecovery',
    type: 'recovery',
    title: '安静恢复日',
    description: '难得有一个能慢下来的日子。没有大声量，但这份平静很重要。',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['恢复', '休息', '日常'],
    actionTypes: ['restAndReflect', 'stableOperation'],
    baseWeight: 8,
    cooldownMonths: 2,
    triggerCondition: (state) => state.stamina <= 55 || state.pressure >= 55 || state.fanFatigue >= 45,
    choices: [
      {
        id: 'sleepWell',
        label: '好好睡一觉',
        description: '优先恢复体力。',
        resultText: '小獭睡了一个很长的觉，醒来时终于没有那么沉了。',
        effects: { stamina: 10, pressure: -5, mood: 3 },
      },
      {
        id: 'sortMessages',
        label: '整理留言',
        description: '从陪伴里恢复心情。',
        resultText: '她慢慢看完大家的留言，知道自己不是一个人在前进。',
        effects: { mood: 7, supportPower: 1, fanFatigue: -4 },
      },
    ],
  },
  {
    id: 'teamAdjustment',
    type: 'recovery',
    title: '团队节奏调整',
    description: '团队意识到近期安排有些紧，于是重新整理了训练、营业和休息的比例。',
    rarity: 'common',
    tone: 'positive',
    triggerTags: ['运营', '恢复', '压力'],
    actionTypes: ['stableOperation', 'restAndReflect'],
    baseWeight: 7,
    cooldownMonths: 3,
    triggerCondition: (state) => state.pressure >= 55 || state.operation >= 35,
    choices: [
      {
        id: 'rebalanceSchedule',
        label: '重排日程',
        description: '用运营力降低消耗。',
        resultText: '安排变得更有余地，小獭终于不用每件事都硬扛。',
        effects: { operation: 3, pressure: -8, stamina: 4 },
      },
      {
        id: 'protectFanBase',
        label: '保护粉丝盘',
        description: '先让应援节奏降温。',
        resultText: '粉丝盘被好好照顾了一次，紧绷感明显下降。',
        effects: { fanFatigue: -10, supportPower: 1, resource: -1 },
      },
    ],
  },
  {
    id: 'firstThousandFans',
    type: 'milestone',
    title: '第一次千人基本盘',
    description: '粉丝数跨过了一个小小的门槛。数字不是全部，但它说明，已经有人愿意认真留下来。',
    rarity: 'rare',
    tone: 'positive',
    triggerTags: ['粉丝', '里程碑', '应援'],
    baseWeight: 12,
    cooldownMonths: 99,
    triggerCondition: (state) =>
      state.fanCount >= 1000 && !state.eventHistory.some((event) => event.eventId === 'firstThousandFans'),
    choices: [
      {
        id: 'thankFans',
        label: '认真道谢',
        description: '把这份支持变成新的约定。',
        resultText: '小獭认真把感谢说出口，粉丝也更确定自己没有喜欢错人。',
        effects: { supportPower: 3, mood: 4, fanFatigue: -3 },
      },
      {
        id: 'keepGoing',
        label: '继续前进',
        description: '把里程碑当成新的起点。',
        resultText: '她没有停在这个数字上，而是把它当作下一段路的起点。',
        effects: { influence: 2, stagePower: 1, pressure: 1 },
      },
    ],
  },
  {
    id: 'stagePowerBreakthrough',
    type: 'milestone',
    title: '舞台力突破',
    description: '她的舞台力终于到了一个新的层级。练习室里的反复确认，开始变成台上的稳定感。',
    rarity: 'rare',
    tone: 'positive',
    triggerTags: ['舞台', '里程碑', '练习'],
    baseWeight: 12,
    cooldownMonths: 99,
    triggerCondition: (state) =>
      state.stagePower >= 60 && !state.eventHistory.some((event) => event.eventId === 'stagePowerBreakthrough'),
    choices: [
      {
        id: 'polishStage',
        label: '继续打磨',
        description: '把突破变成稳定实力。',
        resultText: '小獭没有被一次突破冲昏头，而是继续把舞台力磨得更稳。',
        effects: { stagePower: 3, vocal: 1, dance: 1 },
        b50Bonus: 2,
      },
      {
        id: 'shareConfidence',
        label: '分享自信',
        description: '让粉丝一起记住这次成长。',
        resultText: '粉丝看见了她的成长，也更愿意把下一次舞台交给她。',
        effects: { supportPower: 2, fanCount: 35, mood: 2 },
      },
    ],
  },
];

export const FALLBACK_EVENT: RandomEventConfig = {
  id: 'dailyMoment',
  type: 'recovery',
  title: '普通但重要的一天',
  description: '没有特别大的事件，但小獭还是认真完成了今天的安排。',
  rarity: 'common',
  tone: 'mixed',
  triggerTags: ['日常', '恢复'],
  baseWeight: 1,
  cooldownMonths: 1,
  choices: [
    {
      id: 'steady',
      label: '稳稳收尾',
      description: '保持节奏。',
      resultText: '平凡的一天也有小小积累，小獭把状态保持住了。',
      effects: {
        mood: 2,
        supportPower: 1,
      },
    },
    {
      id: 'earlySleep',
      label: '早点休息',
      description: '让状态轻轻恢复。',
      resultText: '小獭早早睡下，第二天醒来时眼睛又亮了起来。',
      effects: {
        stamina: 6,
        pressure: -3,
      },
    },
  ],
};
