import type { PlanConfig, PlanId } from '../types/game';

export const PLANS: PlanConfig[] = [
  {
    id: 'theaterTraining',
    name: '剧场训练',
    description: '把基础唱跳和舞台表现重新打磨一轮。',
    actionVisualKey: 'theaterTrainingAction',
    primaryStats: ['vocal', 'dance', 'performance'],
    secondaryStats: [],
    riskTags: ['体力下降', '压力上升'],
    eventTags: ['练习', '舞台', '透支'],
    effects: {
      vocal: 6,
      dance: 6,
      performance: 5,
      energy: -10,
      stress: 5,
      fans: 5,
    },
    effectsRange: {
      vocal: [5, 8],
      dance: [5, 8],
      performance: [4, 7],
      energy: [-12, -8],
      stress: [3, 6],
      fans: [0, 8],
    },
    feedbackText: '小獭在剧场里一遍遍练习，基础实力稳稳变强了。',
  },
  {
    id: 'fanService',
    name: '粉丝营业',
    description: '认真回应粉丝，把陪伴感和元气传递出去。',
    actionVisualKey: 'fanServiceAction',
    primaryStats: ['fanLoyalty'],
    secondaryStats: ['charm', 'fans'],
    riskTags: ['压力上升', '体力下降'],
    eventTags: ['粉丝', '营业', '应援'],
    effects: {
      fanLoyalty: 7,
      charm: 3,
      fans: 24,
      energy: -8,
      stress: 4,
    },
    effectsRange: {
      fanLoyalty: [6, 9],
      charm: [2, 4],
      fans: [16, 32],
      energy: [-10, -6],
      stress: [3, 6],
    },
    feedbackText: '小獭给粉丝送出元气 wink，握在手心里的喜欢变多了。',
  },
  {
    id: 'outsideExposure',
    name: '外务曝光',
    description: '参加外部活动和节目，让更多人看见小獭。',
    actionVisualKey: 'outsideExposureAction',
    primaryStats: ['popularity', 'charm'],
    secondaryStats: ['fans'],
    riskTags: ['压力上升', '基础训练不足'],
    eventTags: ['外务', '曝光', '路人盘'],
    effects: {
      popularity: 7,
      charm: 4,
      fans: 28,
      energy: -11,
      stress: 7,
    },
    effectsRange: {
      popularity: [6, 9],
      charm: [3, 5],
      fans: [18, 36],
      energy: [-13, -9],
      stress: [5, 9],
    },
    feedbackText: '外务让小獭被更多人记住，人气和认知度都打开了一点。',
  },
  {
    id: 'stageFocus',
    name: '舞台专项',
    description: '集中打磨舞台记忆点，为重要节点蓄力。',
    actionVisualKey: 'stageFocusAction',
    primaryStats: ['performance'],
    secondaryStats: ['dance', 'fanLoyalty'],
    riskTags: ['体力下降', '压力上升'],
    eventTags: ['舞台', 'B50', '透支'],
    effects: {
      performance: 8,
      dance: 3,
      fanLoyalty: 2,
      fans: 6,
      energy: -13,
      stress: 6,
    },
    effectsRange: {
      performance: [7, 10],
      dance: [2, 4],
      fanLoyalty: [1, 3],
      fans: [0, 10],
      energy: [-15, -11],
      stress: [4, 7],
    },
    feedbackText: '小獭把每一个走位都练到发亮，舞台表现明显更稳了。',
  },
  {
    id: 'imageBuilding',
    name: '形象经营',
    description: '尝试造型、物料和表达方式，建立更鲜明的风格。',
    actionVisualKey: 'imageBuildingAction',
    primaryStats: ['charm'],
    secondaryStats: ['popularity', 'fanLoyalty'],
    riskTags: ['风格争议', '压力上升'],
    eventTags: ['风格', '物料', '讨论'],
    effects: {
      charm: 7,
      popularity: 4,
      fanLoyalty: 2,
      style: 4,
      fans: 14,
      energy: -6,
      stress: 4,
    },
    effectsRange: {
      charm: [6, 9],
      popularity: [3, 5],
      fanLoyalty: [1, 3],
      style: [3, 6],
      fans: [8, 22],
      energy: [-8, -4],
      stress: [2, 6],
    },
    feedbackText: '新的形象方向很适合小獭，可爱里多了一点闪亮的锋芒。',
  },
  {
    id: 'restAndReflect',
    name: '休整沉淀',
    description: '放慢节奏，恢复状态，也重新整理自己的方向。',
    actionVisualKey: 'restAndReflectAction',
    primaryStats: ['energy', 'mood'],
    secondaryStats: ['stress'],
    riskTags: ['成长收益低', '粉丝增长停滞'],
    eventTags: ['休息', '恢复', '沉淀'],
    effects: {
      energy: 24,
      mood: 10,
      stress: -16,
      fans: 0,
    },
    effectsRange: {
      energy: [20, 28],
      mood: [8, 14],
      stress: [-20, -12],
      fans: [0, 4],
    },
    feedbackText: '小獭好好睡了一觉，也把心里的小结轻轻解开了。',
  },
  {
    id: 'stableOperation',
    name: '稳定运营',
    description: '不冒进也不停摆，保持训练、营业和粉丝互动的节奏。',
    actionVisualKey: 'stableOperationAction',
    primaryStats: ['fanLoyalty', 'popularity'],
    secondaryStats: ['vocal', 'dance', 'performance', 'charm'],
    riskTags: ['爆发低', '难以冲顶'],
    eventTags: ['运营', '日常', '低风险'],
    effects: {
      fanLoyalty: 3,
      popularity: 2,
      vocal: 1,
      dance: 1,
      performance: 1,
      charm: 1,
      fans: 14,
      energy: -5,
      stress: 1,
    },
    effectsRange: {
      fanLoyalty: [2, 4],
      popularity: [1, 3],
      vocal: [0, 2],
      dance: [0, 2],
      performance: [0, 2],
      charm: [0, 2],
      fans: [8, 20],
      energy: [-6, -3],
      stress: [0, 2],
    },
    feedbackText: '小獭按自己的节奏稳稳前进，细小的进步也会累积成光。',
  },
];

export const PLAN_BY_ID: Record<PlanId, PlanConfig> = PLANS.reduce(
  (result, plan) => ({
    ...result,
    [plan.id]: plan,
  }),
  {} as Record<PlanId, PlanConfig>,
);
