import type { PlanConfig, PlanId } from '../types/game';
import { ACTION_VARIANT_POOLS } from './actionVariants';
import { CHARACTER_BIRTH_MONTH } from './character';

export const PLANS: PlanConfig[] = [
  {
    id: 'theaterTraining',
    actionPoolId: 'action_theater_training',
    name: '剧场加练',
    description: '把基础唱跳和舞台力重新打磨一轮。',
    actionVisualKey: 'theaterTrainingAction',
    primaryStats: ['vocal', 'dance', 'stagePower'],
    secondaryStats: [],
    riskTags: ['体力下降', '压力上升'],
    eventTags: ['练习', '舞台', '透支'],
    routeTags: ['stage'],
    effects: {
      stamina: -6,
      mood: -1,
      pressure: 4,
      vocal: 1,
      dance: 1,
      stagePower: 2,
      fanCount: 25,
      supportPower: 1,
    },
    effectsRange: {
      stamina: [-8, -5],
      mood: [-1, 0],
      pressure: [3, 5],
      vocal: [0, 2],
      dance: [0, 2],
      stagePower: [1, 3],
      fanCount: [10, 40],
      supportPower: [0, 2],
    },
    variantPool: ACTION_VARIANT_POOLS.action_theater_training,
    feedbackText: '小獭在剧场里一遍遍练习，基础实力稳稳变强了。',
  },
  {
    id: 'fanService',
    actionPoolId: 'action_fan_service',
    name: '粉丝营业',
    description: '认真回应粉丝，把陪伴感和元气传递出去。',
    actionVisualKey: 'fanServiceAction',
    primaryStats: ['supportPower'],
    secondaryStats: ['charm', 'fanCount'],
    riskTags: ['压力上升', '体力下降'],
    eventTags: ['粉丝', '营业', '应援'],
    routeTags: ['fan'],
    effects: {
      stamina: -3,
      mood: 1,
      pressure: 2,
      fanCount: 100,
      supportPower: 2,
      influence: 1,
      charm: 1,
      fanFatigue: 1,
    },
    effectsRange: {
      stamina: [-5, -2],
      mood: [0, 2],
      pressure: [1, 3],
      fanCount: [40, 160],
      supportPower: [1, 4],
      influence: [0, 2],
      charm: [0, 2],
      fanFatigue: [0, 3],
    },
    variantPool: ACTION_VARIANT_POOLS.action_fan_service,
    feedbackText: '小獭给粉丝送出元气 wink，握在手心里的喜欢变多了。',
  },
  {
    id: 'outsideExposure',
    actionPoolId: 'action_media_exposure',
    name: '外务曝光',
    description: '参加外部活动和节目，让更多人看见小獭。',
    actionVisualKey: 'outsideExposureAction',
    primaryStats: ['influence', 'charm'],
    secondaryStats: ['fanCount'],
    riskTags: ['压力上升', '基础训练不足'],
    eventTags: ['外务', '曝光', '路人盘'],
    routeTags: ['outside'],
    effects: {
      stamina: -9,
      mood: 0,
      pressure: 5,
      fanCount: 125,
      supportPower: 0,
      influence: 4,
      resource: 3,
      charm: 1,
      fanFatigue: 1,
    },
    effectsRange: {
      stamina: [-12, -6],
      mood: [-1, 1],
      pressure: [3, 8],
      fanCount: [30, 220],
      supportPower: [-1, 1],
      influence: [2, 6],
      resource: [1, 5],
      charm: [0, 2],
      fanFatigue: [0, 2],
    },
    variantPool: ACTION_VARIANT_POOLS.action_media_exposure,
    feedbackText: '外务让小獭被更多人记住，影响力和认知度都打开了一点。',
  },
  {
    id: 'stageFocus',
    actionPoolId: 'action_stage_focus',
    name: '舞台专项',
    description: '集中打磨舞台记忆点，为重要节点蓄力。',
    actionVisualKey: 'stageFocusAction',
    primaryStats: ['stagePower'],
    secondaryStats: ['dance', 'supportPower'],
    riskTags: ['体力下降', '压力上升'],
    eventTags: ['舞台', 'B50', '透支'],
    routeTags: ['stage'],
    effects: {
      stamina: -11,
      mood: -1,
      pressure: 7,
      vocal: 1,
      dance: 2,
      stagePower: 4,
      fanCount: 15,
      supportPower: 0,
    },
    effectsRange: {
      stamina: [-14, -8],
      mood: [-2, 0],
      pressure: [5, 9],
      vocal: [0, 2],
      dance: [1, 3],
      stagePower: [3, 6],
      fanCount: [5, 30],
      supportPower: [0, 1],
    },
    variantPool: ACTION_VARIANT_POOLS.action_stage_focus,
    feedbackText: '小獭把每一个走位都练到发亮，舞台力明显更稳了。',
  },
  {
    id: 'imageBuilding',
    actionPoolId: 'action_style_building',
    name: '形象经营',
    description: '尝试造型、物料和表达方式，建立更鲜明的风格。',
    actionVisualKey: 'imageBuildingAction',
    primaryStats: ['charm'],
    secondaryStats: ['influence', 'supportPower'],
    riskTags: ['风格争议', '压力上升'],
    eventTags: ['风格', '物料', '讨论'],
    routeTags: ['style'],
    effects: {
      stamina: -4,
      mood: 1,
      pressure: 2,
      fanCount: 50,
      supportPower: 0,
      influence: 2,
      charm: 3,
    },
    effectsRange: {
      stamina: [-6, -3],
      mood: [0, 2],
      pressure: [1, 3],
      fanCount: [20, 80],
      supportPower: [0, 1],
      influence: [1, 4],
      charm: [2, 5],
    },
    variantPool: ACTION_VARIANT_POOLS.action_style_building,
    feedbackText: '新的形象方向很适合小獭，可爱里多了一点闪亮的锋芒。',
  },
  {
    id: 'restAndReflect',
    actionPoolId: 'action_rest_reflect',
    name: '休整沉淀',
    description: '放慢节奏，恢复状态，也重新整理自己的方向。',
    actionVisualKey: 'restAndReflectAction',
    primaryStats: ['stamina', 'mood'],
    secondaryStats: ['pressure'],
    riskTags: ['成长收益低', '粉丝增长停滞'],
    eventTags: ['休息', '恢复', '沉淀'],
    routeTags: ['recovery'],
    effects: {
      stamina: 12,
      mood: 7,
      pressure: -11,
      operation: 1,
      fanFatigue: -2,
    },
    effectsRange: {
      stamina: [8, 16],
      mood: [4, 10],
      pressure: [-15, -8],
      operation: [0, 2],
      fanFatigue: [-3, -1],
    },
    variantPool: ACTION_VARIANT_POOLS.action_rest_reflect,
    feedbackText: '小獭好好睡了一觉，也把心里的小结轻轻解开了。',
  },
  {
    id: 'stableOperation',
    actionPoolId: 'action_steady_operation',
    name: '稳定运营',
    description: '不冒进也不停摆，保持训练、营业和粉丝互动的节奏。',
    actionVisualKey: 'stableOperationAction',
    primaryStats: ['supportPower', 'influence'],
    secondaryStats: ['vocal', 'dance', 'stagePower', 'charm'],
    riskTags: ['爆发低', '难以冲顶'],
    eventTags: ['运营', '日常', '低风险'],
    routeTags: ['stable'],
    effects: {
      stamina: -2,
      mood: 1,
      pressure: -4,
      fanCount: 15,
      supportPower: 3,
      influence: 1,
      resource: 1,
      operation: 3,
      fanFatigue: -2,
    },
    effectsRange: {
      stamina: [-4, -1],
      mood: [0, 3],
      pressure: [-6, -2],
      fanCount: [0, 30],
      supportPower: [2, 5],
      influence: [0, 2],
      resource: [0, 2],
      operation: [2, 5],
      fanFatigue: [-4, -1],
    },
    variantPool: ACTION_VARIANT_POOLS.action_steady_operation,
    feedbackText: '小獭按自己的节奏稳稳前进，细小的进步也会累积成光。',
  },
  {
    id: 'specialSoloWork',
    name: '个人外务',
    description: '独立参加外部企划，扩大路人认知和讨论度。',
    actionVisualKey: 'specialSoloWorkAction',
    primaryStats: ['influence', 'charm'],
    secondaryStats: ['fanCount'],
    riskTags: ['压力明显上升', '体力下降'],
    eventTags: ['外务', '曝光', '舆论'],
    routeTags: ['outside'],
    isSpecialAction: true,
    unlockConditionMode: 'any',
    lockedReason: '需要影响力 ≥ 40，或总选达到 TOP32，或经历过正向外务 / 曝光事件。',
    unlockConditions: [
      { type: 'statAtLeast', stat: 'influence', value: 40 },
      { type: 'electionTierAtLeast', tier: 'top32' },
      { type: 'eventTagSeen', tag: '外务', tone: 'positive' },
      { type: 'eventTagSeen', tag: '曝光', tone: 'positive' },
    ],
    effects: {
      influence: 10,
      charm: 5,
      fanCount: 46,
      stamina: -14,
      pressure: 10,
    },
    effectsRange: {
      influence: [9, 13],
      charm: [4, 7],
      fanCount: [36, 62],
      stamina: [-17, -12],
      pressure: [8, 13],
    },
    feedbackText: '这次个人外务让更多人记住了小獭，也让她背上了更高期待。',
  },
  {
    id: 'specialIntensiveTraining',
    name: '高强度集训',
    description: '短期集中冲刺基础能力，但需要扛住透支风险。',
    actionVisualKey: 'specialIntensiveTrainingAction',
    primaryStats: ['vocal', 'dance', 'stagePower'],
    secondaryStats: ['pressure'],
    riskTags: ['体力大幅下降', '压力明显上升'],
    eventTags: ['练习', '舞台', '透支'],
    routeTags: ['stage'],
    isSpecialAction: true,
    lockedReason: '需要体力 ≥ 60，且压力 ≤ 65。',
    unlockConditions: [
      { type: 'statAtLeast', stat: 'stamina', value: 60 },
      { type: 'statAtMost', stat: 'pressure', value: 65 },
    ],
    effects: {
      vocal: 10,
      dance: 10,
      stagePower: 10,
      stamina: -24,
      pressure: 16,
      mood: -3,
    },
    effectsRange: {
      vocal: [9, 13],
      dance: [9, 13],
      stagePower: [10, 14],
      stamina: [-28, -22],
      pressure: [13, 18],
      mood: [-5, -1],
    },
    feedbackText: '小獭咬牙完成了高强度集训，实力被狠狠向前推了一步。',
  },
  {
    id: 'specialBirthdaySupport',
    name: '生日应援筹备',
    description: '提前凝聚粉丝心意，把重要月份变成共同记忆。',
    actionVisualKey: 'specialBirthdaySupportAction',
    primaryStats: ['supportPower', 'fanCount'],
    secondaryStats: ['mood'],
    riskTags: ['压力小幅上升'],
    eventTags: ['粉丝', '应援', '生日'],
    routeTags: ['fan'],
    isSpecialAction: true,
    availableMonths: [CHARACTER_BIRTH_MONTH - 1, CHARACTER_BIRTH_MONTH],
    lockedReason: `仅 ${CHARACTER_BIRTH_MONTH - 1} 月 / ${CHARACTER_BIRTH_MONTH} 月开放，且核心应援力 ≥ 35。`,
    unlockConditions: [
      { type: 'monthIn', months: [CHARACTER_BIRTH_MONTH - 1, CHARACTER_BIRTH_MONTH] },
      { type: 'statAtLeast', stat: 'supportPower', value: 35 },
    ],
    effects: {
      supportPower: 10,
      fanCount: 70,
      mood: 8,
      pressure: 4,
    },
    effectsRange: {
      supportPower: [9, 13],
      fanCount: [52, 86],
      mood: [6, 10],
      pressure: [3, 6],
    },
    feedbackText: '生日应援的准备让小獭和粉丝靠得更近，喜欢也变得更有形状。',
  },
  {
    id: 'specialStyleShift',
    name: '风格转型',
    description: '尝试更鲜明的表达方式，提高辨识度也承担争议。',
    actionVisualKey: 'specialStyleShiftAction',
    primaryStats: ['charm', 'operation'],
    secondaryStats: ['influence', 'supportPower'],
    riskTags: ['风格争议', '压力上升'],
    eventTags: ['风格', '形象', '舆论'],
    routeTags: ['style'],
    isSpecialAction: true,
    lockedReason: '需要魅力 ≥ 45，且形象经营累计 ≥ 3 次。',
    unlockConditions: [
      { type: 'statAtLeast', stat: 'charm', value: 45 },
      { type: 'planCountAtLeast', planId: 'imageBuilding', count: 3 },
    ],
    effects: {
      charm: 10,
      operation: 8,
      influence: 6,
      supportPower: 2,
      pressure: 8,
      stamina: -6,
    },
    effectsRange: {
      charm: [9, 13],
      operation: [7, 11],
      influence: [4, 8],
      supportPower: [-1, 4],
      pressure: [6, 10],
      stamina: [-8, -4],
    },
    feedbackText: '新的风格让小獭更有辨识度，也让讨论声变得更热烈。',
  },
];

export const PLAN_BY_ID: Record<PlanId, PlanConfig> = PLANS.reduce(
  (result, plan) => ({
    ...result,
    [plan.id]: plan,
  }),
  {} as Record<PlanId, PlanConfig>,
);
